        .PAGE   1
        .ROM
        .BIOS
        .BIOSVARS
        .ZILOG                  ; I want to use standard Z80 syntax

FROM_X  EQU     50              ;! starting (left) x-coordinate of the line
TO_X    EQU     256-FROM_X      ;! ending (right) x-coordinate of the line
FROM_Y  EQU     90              ;! starting (top) y-coordinate of the line
TO_Y    EQU     212-FROM_Y      ;! ending (bottom) y-coordinate of the line

LEVELS  EQU     8               ;! number of available colors

ERROR   EQU     $E000           ;! Accumulated "error"
THR     EQU     ERROR+1         ;! Start of threshold table
DX      EQU     THR+LEVELS-1    ;! height of the line
DY      EQU     DX+1            ;! width of the line

        ; start by calculation of initial values for accumulators
        ld      a,TO_X
        sub     FROM_X          ; a = dx
        ld      (DX),a
        ld      ix,THR
        ld      d,0
        ld      e,a             ; de = dx
        ld      hl,0            ; hl = k * dx
        ld      b,LEVELS-1
@@thrloop:
        add     hl,de
        push    hl
        ; now divide hl by 8
        srl     h
        rr      l
        srl     h
        rr      l
        srl     h
        rr      l
        ld      (ix),l
        inc     ix
        pop     hl
        djnz    @@thrloop

        ld      a,TO_Y
        sub     FROM_Y          ; a = dy
        ld      (DY),a
        xor     a
        ld      (ERROR),a

        ; set colors
        ld      a,$FF           ; white
        ld      (FORCLR),a
        xor     a
        ld      (BAKCLR),a
        ld      (BDRCLR),a
        call    CHGCLR
        ; now enter screen 8
        ld      a,8
        call    CHGMOD

        ; load appropriate port numbers and hot-patch the code
        ld      a,(VDP_DW)
        ld      (@@port5+1),a
        inc     a
        ld      (@@port1+1),a
        ld      (@@port2+1),a
        ld      (@@port3+1),a
        ld      (@@port4+1),a
        ; now draw line pixel by pixel
        ld      h,FROM_Y
        ld      l,FROM_X
@@draw:
        ; in this loop we suppose that h is set to Y and l to X

        ; start by determining color of the lower pixel (with bigger Y)
        ld      a,(ERROR)
        ld      ix,THR
        ld      b,LEVELS-1
@@loop: ld      c,(ix)
        cp      c
        jr      c,@@cont        ; accumulated error < threshold1
        inc     ix              ; next threshold
        djnz    @@loop
@@cont:
        ld      ix,COLORS
        ld      c,b
        ld      b,0
        push    bc
        add     ix,bc
        ld      a,(ix)
        ; now in a we have a color of pixel (X, Y+1)
        inc     h
        call    @@PSET
        dec     h
        pop     bc
        ld      ix,COLORS
        ld      a,c
        neg
        add     a,LEVELS-1
        ld      c,a
        add     ix,bc
        ld      a,(ix)
        call    @@PSET

        ; are we done?
        ld      a,l
        cp      TO_X
        jr      z,@@end

        ; now adjust error
        ld      a,(DX)
        ld      b,a             ; b = dx
        ld      a,(DY)
        ld      c,a             ; c = dy
        ld      a,(ERROR)       ; a = E
        add     a,c             ; a = E + dy
        jr      c,@@sub         ; if it is overflow, surely sum >= dx
        cp      b               ; try to decrease it by dx
        jr      c,@@cont2       ; failure, it was less than dx
@@sub:
        ; if we are here, we need to decrease A by dx and advance Y
        sub     b
        inc     h
@@cont2:
        ld      (ERROR),a
        inc     l
        jr      @@draw

@@end:
        jr      @@end

;! put on screen 8 a pixel (l, h) with color in a
@@PSET:
        ld      c,a             ;store color
        ld      a,h
        rlca
        rlca
        and     $03             ; two highest bits of Y coordinate
        di                      ; now we're going to talk to VDP
@@port1:
        out     ($99),a
        ld      a,$80|14        ; we're going to write them to register 14
@@port2:
        out     ($99),a         ; now we have two highest bits of Y in R14
        ld      a,l
@@port3:
        out     ($99),a         ; write X
        ld      a,h
        and     00111111b       ; now extract low 6 bits of Y
        or      01000000b       ; and set right VDP command
@@port4:
        out     ($99),a         ; write low 6 bits of Y (high ones are in R14) and command
@@port5:
        ld      a,c
        out     ($98),a         ; write color
        ei                      ; we're done
        ret

COLORS:                         ;! the color shades, from the most bright to black
        ; GGGRRRBB
        .DB     7<<5
        .DB     6<<5
        .DB     5<<5
        .DB     4<<5
        .DB     3<<5
        .DB     2<<5
        .DB     1<<5
        .DB     0               ; black
